### ISSUE TITLE
Other plataform ports?

### ISSUE THREAD

**Issue by VittoScaletta** [v-atamanenko/deadspace-vita#11]
Would it be possible to port this on PC or maybe on vita3k ? thanks!

**Comment by v-atamanenko** [comment]
@VittoScaletta for the foreseeable future, it wouldn't be possible to play this on Vita3K (due to lack of kernel plugins support), but I heard that people succeeded in running it via normal android emulators like BlueStacks. This is out of the scope of this project though, so I will be closing the issue

**Comment by VittoScaletta** [comment]
Alright! thanks, I've seen how it works on the real vita and it's incredible, just wondered because of the zero-G gravity part, on emulators I always got stuck there since I can't shake it vertically!
